### PR TITLE
Fix For TBA Issue

### PR DESCRIPTION
**Pull request by JonnyBoy333**
I've been trying to get a fix in place for an issue caused when using token based authentication. This was brought up in #11. The issue is caused when asked your password even though the sdfcli doesn't require it and having it output your password for the subsequent question.

The fix for this was a little involved because currently, the extension assumes a password is always needed when using sdfcli commands. In order to accommodate both tokens and regular passwords, I'm proposing that the user only be required to enter their password when the sdfcli indicates that it is necessary. Which you can tell when it says "Using user credentials." instead of when the config is initialized.

I've done a bit of testing with both password and token based projects using the vscode actions as well as the new tree functionality (very cool, btw) and this approach seems to work well. Please give it a test and tell me what you think. There is also a fix in here to a bug in filtering multi-select results.

### CODE REVIEW

**Comment by JonnyBoy333** [comment]
I also put the fix for the windows filepath issue in here. Issue #3.

**Comment by christopherwxyz** [comment]
Let me pull these in to my local branch to do some QA. Thanks for the contrib!

**Comment by christopherwxyz** [comment]
Tested for import files, objects, list files, objects, and I also ran other commands to test deploy, such as validate, preview, and deploy. 

Expectations: TBA recognized, password prompt is not given, and commands are executed as normal.
Observations: No issues with these functions.

I approved this PR.

**Comment by christopherwxyz** [comment]
@mark-keaton Could you please merge this in after your review?

**Pull request merged**
